<?php

/**
* @file
* Module file for my first test form
*/


function testmodule_menu()
{
  $items = array();

  $items['myexamples/myformexample'] = array(
    'title' => 'My Example form',
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('testmodule_form'),
    'access callback' => TRUE
  );

  return $items;
}



function testmodule_form($form, &$form_state)
{
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );

  return $form;
}



function testmodule_form_validate($form, &$form_state)
{
  
}


function testmodule_form_submit($form, &$form_state)
{

}
