# My makefile for README.adoc
#
# README.adoc is written in AsciiDoc, a nice markup language for
# documentation. It produces beautiful html and other formats. To get a
# html output, just run `asciidoctor README.adoc` and it will produce a
# html as default.

BASEFILENAME = README

all: $(BASEFILENAME).adoc
	asciidoctor $(BASEFILENAME).adoc
