<?php

/**
 * @file
 * Module file for my Nickel play module
 */


/**
 * Implements hook_menu().
 */
function nickelplay_menu()
{
  $items = array();

  $items['nickelplay'] = array( // This creates a URL that
                                // will call this form at "nickelplay"
    'title' => 'Nickel Play Time', //page title
    'description' => 'A form for playing with nickel indices',
    'page callback' => 'drupal_get_form',  // This is the function that will
                                           // be called when the page is
                                           // accessed.  for a form, use
                                           // drupal_get_form
    'page arguments' => array('nickelplay_form'),
    'access callback' => TRUE,
  );

  return $items;
}



function nickelplay_form($form, &$form_state)
{
  // This is how you insert HTML into a form:
  $form['html_text'] = array(
    '#markup' => t('<p>Hello there. You are reading me right now!</p>')
  );

  $form['nickel'] = array(
    '#type' => 'textfield',
    '#title' => 'Nickel Index:',
    '#size' => 60,
    '#required' => TRUE, //make this field required
  );

  // dpm($form_state);
  if (isset($form_state['imagepath']))
  {
    $form['html_text1'] = array(
      '#markup' => t('<img src="'. $form_state['imagepath'] .
                      ' "alt="alternative text">')
      );
  }

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );

  return $form;
}



function nickelplay_form_validate($form, &$form_state)
{
  $nickel_value_given = $form_state['values']['nickel'];
  $exec1 = "python sites/default/scripts/minimalnickel.py \"$nickel_value_given\" 2>&1";
  $nickel_value_correct = trim( shell_exec($exec1) ); // Correct Nickel Index
                          // calculated by script.  trim() was needed here
                          // because shell_exec() produced one unwanted
                          // whitespace at the end of the output string

  if ( strlen($nickel_value_given) != strlen($nickel_value_correct) )
  {
    form_set_error('nickel', t("Your nickel index \"$nickel_value_given\" seems to be completely wrong. Please check if it is according to the conventions.") );
    return 0;
  }
  else if ( $nickel_value_given != $nickel_value_correct )
  {
    form_set_error('nickel', t('The given nickel index:"@ni_given" is not correct (minimal). The right Nickel Index is:"@ni_correct".',
      array(
        '@ni_given' => $nickel_value_given,
        '@ni_correct' => $nickel_value_correct,
      )
    ));
  }
  else
  {
    drupal_set_message(t('The Nickel index "@nickel" is correct!',
      array('@nickel' => $nickel_value_correct)
    ));
  }

  // Generate Picture to Nickel Index
  $image_path = "sites/default/files/tmp/" . uniqid($nickel_value_correct);
                 // this is the path to the dot file the image (svg) file will
                 // have an extra ending of ".svg"
  $script_path = "sites/default/scripts/neato_from_nickel.py";
  exec(escapeshellcmd("python $script_path $nickel_value_correct $image_path"));
  $form_state['imagepath'] = $image_path . ".svg";
}


function nickelplay_form_submit($form, &$form_state)
{
  $form_state['rebuild'] = TRUE;
}
