#! /bin/bash

# Make a backup of the drupal files with tar into a file in the current
# directory.


# Create string for the current date. In the format
# "2015-02-23T15:45:12"
date=$(date +%Y-%m-%dT%H:%M:%S)

# Save current directory.
here=$(pwd)

echo "Go to Loopedia folder..."
cd /home/pcl305/loopedia/sites/default/

echo "Make backup with tar..."
tar -czf "${here}/files_${date}.tgz" "files"
